name: Deploy to EC2

on:
  push:
    branches:
      - develop  # запускать только при пуше в ветку develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy project files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."  # всё содержимое репозитория
        target: "~/guess-the-prompt-backend"  # путь на сервере

    - name: Connect to EC2 and run Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/guess-the-prompt-backend
          docker compose down
          docker compose up -d --build


